--DROP TABLE LIKEHATE;
--DROP SEQUENCE LIKEHATE_SEQ;

-- 좋아요 기능 구현

CREATE TABLE LIKEHATE 
(
  LIKE_IDX NUMBER NOT NULL,
  LIKE_CHECK NUMBER DEFAULT 0
, REVIEW_IDX NUMBER NOT NULL unique
, USER_IDX NUMBER NOT NULL 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    LIKE_IDX 
  )
  ENABLE
);

--ALTER TABLE LIKEHATE
-- ADD CONSTRAINT FK_REVIEW_IDX FOREIGN KEY(REVIEW_IDX) REFERENCES REVIEW(REVIEW_IDX);
--ALTER TABLE LIKEHATE
--  ADD CONSTRAINT FK_USER_IDX FOREIGN KEY(USER_IDX) REFERENCES MEMBER_USER(USER_IDX);


CREATE SEQUENCE LIKEHATE_SEQ;

INSERT INTO LIKEHATE
VALUES (LIKEHATE_SEQ.NEXTVAL,0,1,0);

INSERT INTO LIKEHATE
VALUES (LIKEHATE_SEQ.NEXTVAL,0,2,0);

INSERT INTO LIKEHATE
VALUES (LIKEHATE_SEQ.NEXTVAL,0,3,0);

INSERT INTO LIKEHATE
VALUES (LIKEHATE_SEQ.NEXTVAL,0,4,0);

INSERT INTO LIKEHATE
VALUES (LIKEHATE_SEQ.NEXTVAL,0,5,0);

INSERT INTO LIKEHATE
VALUES (LIKEHATE_SEQ.NEXTVAL,0,6,0);

COMMIT;